### ISSUE TITLE
Feature - Know this and still learning buttons on each flash card  

### ISSUE THREAD

**Issue by mkudith** [csc510-fall22-p2-g33/FlashCards#1]
![image](https://user-images.githubusercontent.com/7265270/201502046-2a9e98fa-980b-4ef1-8343-4dbd6fe88211.png)

**Comment by SutapaDeyTithi** [comment]
Added the buttons!


![Image](https://user-images.githubusercontent.com/64492414/205375997-d8ebe23f-21bd-4234-971c-6cc09683e44c.png)

**Comment by SutapaDeyTithi** [comment]
The buttons are working on frontend!



![Image](https://user-images.githubusercontent.com/64492414/205459221-22c5e6b8-74d9-4455-99e0-419bf7b6a2ab.png)

**Comment by SutapaDeyTithi** [comment]
working in the final version.
