### ISSUE TITLE
Feature - Star your cards 

### ISSUE THREAD

**Issue by mkudith** [csc510-fall22-p2-g33/FlashCards#2]
![image](https://user-images.githubusercontent.com/7265270/201502078-91fca843-7991-433b-bbe8-6b9cc140a508.png)

**Comment by SutapaDeyTithi** [comment]
Added the bookmark star!

There is an issue, the earlier code is written in a way that wherever you click on a card, the card flips, so you can operate other buttons on the card. Have to fix it.


![Image](https://user-images.githubusercontent.com/64492414/205378549-6c2f246a-5e97-44a0-ad70-dadeab187f19.png)

**Comment by SutapaDeyTithi** [comment]
Bookmark is working on the frontend!


![Image](https://user-images.githubusercontent.com/64492414/205459246-039b63b9-7e21-4dd4-b217-193b5f03c4b6.png)

**Comment by SutapaDeyTithi** [comment]
Working.
