### ISSUE TITLE
Add more sign-in providers w/ Firebase Authentication

### ISSUE THREAD

**Issue by sreedhara-aneesh** [csc510-fall22-p2-g33/FlashCards#29]
### Discussed in https://github.com/csc510-fall22-p2-g33/FlashCards/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **sreedhara-aneesh** November 16, 2022</sup>
Users should be able to sign in with external accounts (Google, Apple, Microsoft, etc) rather than being forced to create a new account solely for this application. Firebase Authentication allows for simple, secure authorization flows. The ability to easily add new authentication flows/providers as we see fit over time will benefit the scalability of this application.</div>

**Comment by sreedhara-aneesh** [comment]
I have this working locally with an implementation that allows you to register with Google. Waiting on #27 to get merged before I mess with anything.

**Comment by mkudith** [comment]
LGTM 🚢
