### ISSUE TITLE
Feature - Read your cards loud 

### ISSUE THREAD

**Issue by mkudith** [csc510-fall22-p2-g33/FlashCards#3]
![image](https://user-images.githubusercontent.com/7265270/201502092-aa90d24c-d5e0-4d2b-a65e-889b9ab73ab9.png)

**Comment by SutapaDeyTithi** [comment]
Cards can be read out loud!


![Image](https://user-images.githubusercontent.com/64492414/205778737-82e443f0-219f-4317-a23f-44fa5b8547db.png)

**Comment by SutapaDeyTithi** [comment]
This feature works now.
